### ISSUE TITLE
android:dexAggregate java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by dejvid** [pfn/protify#16]
Just enabled protify in my android project and cant get  it running.

Im using sbt build  and this plugins:

```
addSbtPlugin("org.scala-android" % "sbt-android" % "1.6.3")
addSbtPlugin("org.scala-android" % "sbt-android-protify" % "1.2.2")
```

This is full output from sbt

```
> reload
[info] Loading project definition from /Users/dejvid/Dev/someApp/mobile/project
[info] Set current project to someApp Android (in build file:/Users/dejvid/Dev/someApp/mobile/)
[info] Set current project to someApp Android (in build file:/Users/dejvid/Dev/someApp/mobile/)
c> clean
[warn] Errors during XML parse:
[warn] Additionally, the fallback loader failed to parse the XML.
a[success] Total time: 2 s, completed May 24, 2016 12:05:15 PM 
> protify
[info] Updating {file:/Users/dejvid/Dev/someApp/mobile/}mobileCommon...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Updating {file:/Users/dejvid/Dev/someApp/mobile/}someAppAndroid...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 20 Scala sources and 2 Java sources to /Users/dejvid/Dev/someApp/mobile/mobile/target/scala-2.11/classes...
[info] Collecting resources
[info] Performing full resource merge
[info] Processing resources
[info] Packaging resources: resources-debug.ap_
[warn] bootstrap class path not set in conjunction with -source 1.7
[info] Packaging /Users/dejvid/Dev/someApp/mobile/mobile/target/scala-2.11/someApp-mobile-common-library_2.11-0.1.0.jar ...
[info] Done packaging.
[info] Compiling 119 Scala sources and 15 Java sources to /Users/dejvid/Dev/someApp/mobile/android/target/android/intermediates/classes...
[info] Packaging /Users/dejvid/Dev/someApp/mobile/android/target/android/intermediates/classes.jar ...
[info] Done packaging.
[trace] Stack trace suppressed: run last someAppAndroid/android:dexAggregate for the full output.
[error] (someAppAndroid/android:dexAggregate) java.lang.NoSuchMethodError: android.Aggregate$Dex.copy$default$7()Lcom/android/sdklib/BuildToolInfo;
[error] Total time: 41 s, completed May 24, 2016 12:06:03 PM
> last someAppAndroid/android:dexAggregate
java.lang.NoSuchMethodError: android.Aggregate$Dex.copy$default$7()Lcom/android/sdklib/BuildToolInfo;
        at android.protify.Keys$$anonfun$protifySettings$9.apply(plugin.scala:143)
        at android.protify.Keys$$anonfun$protifySettings$9.apply(plugin.scala:134)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (someAppAndroid/android:dexAggregate) java.lang.NoSuchMethodError: android.Aggregate$Dex.copy$default$7()Lcom/android/sdklib/BuildToolInfo;
> 

```

But using addSbtPlugin("org.scala-android" % "sbt-android" % "1.6.2") works fine ?!

**Comment by pfn** [comment]
I will need to update protify, a binary incompatible change occurred
